#ifndef __MAIN_RECEIVER_H__
#define __MAIN_RECEIVER_H__

#define		PPM_CH1_PIN		GPIO_PIN_0
#define		PPM_CH1_PORT	GPIOB

#define		PPM_CH2_PIN		GPIO_PIN_1
#define		PPM_CH2_PORT	GPIOB

#define		PPM_CH3_PIN		GPIO_PIN_8
#define		PPM_CH3_PORT	GPIOB

#define		PPM_CH4_PIN		GPIO_PIN_9
#define		PPM_CH4_PORT	GPIOB

#define		PPM_CH5_PIN		GPIO_PIN_0
#define		PPM_CH5_PORT	GPIOA

#define		PPM_CH6_PIN		GPIO_PIN_1
#define		PPM_CH6_PORT	GPIOA

#define		PPM_CH7_PIN		GPIO_PIN_2
#define		PPM_CH7_PORT	GPIOA

#define		PPM_CH8_PIN		GPIO_PIN_3
#define		PPM_CH8_PORT	GPIOA

#define		PPM_SBUS_PIN	GPIO_PIN_8
#define		PPM_SBUS_PORT	GPIOA


#endif

